language: objective-c  #1
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=SwiftMKitDemo
osx_image: xcode7.3 #2
xcode_workspace: SwiftMKitDemo/SwiftMKitDemo.xcworkspace #3
xcode_scheme: SwiftMKitDemo #4
xcode_sdk: iphonesimulator9.3 #5