source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!

def pods
    pod 'SwiftMKit_Demo', '~> 1.1.5.3'
    
    pod 'Charts', '~> 3.1.0'
    pod 'PulsingHalo', '~> 0.2.0'
    pod 'FDFullscreenPopGesture', '~> 1.1'
    pod 'AudioKit', '~> 4.3.0'
end

target 'SwiftMKitDemo' do
    pods
end

target 'SwiftMKitDemoTests' do
    pods
end

target 'SwiftMKitDemoUITests' do
    pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.1'
    end
  end
end
