source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

use_frameworks!

def pods
    pod 'CocoaLumberjack/Swift', '~> 3.0.0'
    pod 'ReactiveCocoa', '~> 5.0.0'
    pod 'Alamofire', '~> 4.2.0'
    pod 'ReachabilitySwift', '~> 3'
    pod 'MagicalRecord', '~> 2.3.0'
    pod 'MJExtension', '~> 3.0.0'
    pod 'MJRefresh', '~> 3.1.0'
    pod 'EZSwiftExtensions', '~> 1.7.0'
    pod 'JSPatch', '~> 1.1.0'
#    pod 'CryptoSwift', '~> 0.6.9'
    pod 'IQKeyboardManager', '~> 4.0.0'
    pod 'WebViewJavascriptBridge', '~> 5.0.0'
    pod 'PINCache', '~> 2.3.0'
    pod 'SnapKit', '~> 3.0.0'
    pod 'pop', '~> 1.0.0'
    pod 'Aspects', '~> 1.4.0'
    pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift', :branch => 'feature/swift-3'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'Charts', '~> 3.0.0'
    pod 'PulsingHalo', '~> 0.2.0'
    pod 'FDFullscreenPopGesture', '~> 1.1'
#    pod 'Player', '~> 0.2.0'
end

target 'SwiftMKitDemo' do
    pods
end

target 'SwiftMKitDemoTests' do
    pods
end

target 'SwiftMKitDemoUITests' do
    pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
