source 'https://github.com/CocoaPods/Specs.git'

link_with 'SwiftMKitDemoTests', 'SwiftMKitDemoUITests'  

platform :ios, '8.0'

use_frameworks!

pod 'CocoaLumberjack/Swift'
pod 'ReactiveCocoa'
pod 'Alamofire'
pod 'MagicalRecord'
pod 'MagicalRecord/CocoaLumberjack'
pod 'MJExtension'
pod 'MJRefresh'
pod 'HanekeSwift'
pod 'MBProgressHUD'